### ISSUE TITLE
Controller right next to Source issue

### ISSUE THREAD

**Issue by SirLovi** [ScreepsGamers/screeps.behaviour-action-pattern#109]
The code has problems to distinguish which container is for the upgrader.
(There is another container under the harvester)

![capture](https://cloud.githubusercontent.com/assets/20193391/18273785/5c5f7d3a-743f-11e6-9545-5b56cd3b84da.PNG)

**Comment by cyberblast** [comment]
yes, thats right. I have the same problem in one of my rooms. it will work if you place one of them out of the range of the source while in range of the controller (__current workaround__). 

Problem is: currently containers are IN or OUT. 
IN is for the miner and the hauler will get its energy
OUT is for the upgrader and the hauler will fill it. 

The container you need would be both, wich is not supported (currently). 
Will surely need a fix.

**Comment by cyberblast** [comment]
Proposed solution outline: 

* The container gets filled by miner 
* The container gets used by the upgrader
* Main problem is the hauler
  * The hauler _could_ ignore the container. problem solved. 
  * But, as "upgrading" is the final desired action, as much energy as possible should go there. What about the other energy...
  * sending "as much energy as possible" into that container will also be a bad idea, because then the container is full and the miner can't mine :-1: 
  * The hauler should send some energy when it's quite empty (below x%) :+1:  
  * And take energy when its quite full
* To reach that we need to define a better classification of the containers
  * pure miner container (like current IN) - will be emptied by haulers
  * versatile OUT (like current OUT) - will be filled by haulers
  * managed containers
    * a container that should never be empty and never be full
    * filled AND emptied by haulers
  * an additional property may be if its the container for the upgrader (in addition to its class)
* container classification will be evaluated once and then stored into memory
* room will be extended with those properties
  * containers (all container)
  * upgraderContainer (0 or 1 container)
  * chargeablesIn  
    Containers (and Links), haulers shall take energy from, including managed (when full)
  * chargeablesOut  
    Containers (and Links), haulers shall put energy into, including managed (when empty)

**Comment by cyberblast** [comment]
Does anybody want to implement this one?

**Comment by mikiones** [comment]
i working on auto extensions and containers  atm.

**Comment by cyberblast** [comment]
Gonna implement it in branch ContainerClassification 
https://github.com/cyberblast/screeps.behaviour-action-pattern/tree/ContainerClassification 
and merge into dev when complete...
