### ISSUE TITLE
Improve invade system

### ISSUE THREAD

**Issue by torin555** [ScreepsGamers/screeps.behaviour-action-pattern#150]
At the moment invading doesn't really work. When you invade your combat creeps move towards the invade flag (not really attacking things along the way, such as defensive creeps that are murdering them.) Once they get to the invade flag the one that got there first will sit on it saying NO PATH while the others will be honking because they can't get on top of the flag.

**Comment by torin555** [comment]
Melee attackers will attack whatever is on the flag location, ranged attackers do not seem to attack anything.

**Comment by cyberblast** [comment]
Anybody has a fitting victim to elaborate this one?

**Comment by cyberblast** [comment]
I believe this bug is already fixed. But maybe somebody can double check if invading using a red/red flag works. 
What has not been changed is that invading creeps don't attack 'everything' along their way. This is by design... 
For a better logic regarding this aspect it is required to have a way to differentiate of what is an enemy and whats not (=> #42).
