### ISSUE TITLE
Latest Build issues

### ISSUE THREAD

**Issue by Animatrixy** [ScreepsGamers/screeps.behaviour-action-pattern#197]
So i got wiped out again ;-( so i updated to the latest dev branch and restarted my room, however everything was ok till my controller updated to lvl2 now all my workers just sit there even though there is stuff to build, my haulers do nothing either, i have got storage at each source (not minerals) and the controller but nothing is doing they all sit there, nothing has been changed in the scripts at all its a fresh setup, any ideas ?

Thanks
K

**Comment by Animatrixy** [comment]
Edit, only seems to be an issue when haulers spawn ?

**Comment by mikiones** [comment]
do you have miners? yet

**Comment by Animatrixy** [comment]
yes i have 1, when the haulers spawn the workers goto idle, unless i kill the hauler then everything carries on ok

**Comment by cyberblast** [comment]
Do you have miners? 
As soon as haulers are spawning, workers are not allowed to harvest anymore. Its only the miners job to do so.

**Comment by Animatrixy** [comment]
Seems like also my upgrader is saying unable to dtermine working location, even though there is a container next to the controller ?

**Comment by cyberblast** [comment]
This is because both containers next to the controller are considered as "upgrader containers". the upgrader tries to get in range of both. 
Better: build only one container at x41 y11. such container will be considered as mixed (managed container) for both the source and the controller.

**Comment by Gestic** [comment]
tried to mess with the spawn.room.storage & miner pop count on lines 19 - 21 but with little luck trying to figure it out.. anyways  && spawn.room.population.typeCount['miner'] is there twice .. this right? I deleted my storage units and it doesnt spawn haulers which seems to be if not the cause, the effect anyways. shouldnt miners spawn first? havent had any spawn, just the haulers which freezes workers

**Comment by cyberblast** [comment]
hm Yes I think there is something wrong. when haulers spawn, workers stop mining, because miners should spawn first. But currently haulers will also spawn as soon as there is a storage or an 'out' container. Even if there are no miners. So this makes no sense. 
I'll change it to ensure that haulers will only spawn when there are miners around.

**Comment by Animatrixy** [comment]
The haulers spawn first because the min energy is lower for haulers than miners, so I fixed it by changing haulers min energy to more than miners

**Comment by Gestic** [comment]
ah nice.. yeah works after level 2 which does seem to point to energy as you said. seems like a logic issue of spawning which made me think to look at those lines as i said. if miners > 0 && energy >= min ? wish i could help but i only started doing js since this game :p

**Comment by cyberblast** [comment]
The min energy threshold is not the problem. This min energy logic comes on top to ensure creeps have a good size and the hive is not running dry. 
The condition allowing haulers to spawn is, that there are miners. 
Because miners are designed slow moving and should never move away from their source, they require haulers. When there are no miners there are only workers, which don't require haulers.
