### ISSUE TITLE
FlagDir find should use map.findRoute instead of room range

### ISSUE THREAD

**Issue by cyberblast** [ScreepsGamers/screeps.behaviour-action-pattern#220]
current range calculation does not take into account which room is accessible (exit). 
Game.map.findRoute can be used for a better range calculation. 
Sample is available in creep.js (Creep.prototype.getPath). 

This is important for privateers, deciding which room to exploit and to ignore rooms without direct access (going long detours).

**Comment by cyberblast** [comment]
Way too expensive to calculate each time

**Comment by Dasku** [comment]
Not sure if this is a related bug to this or the recent pathfinding stuff, but 3 of my privateers are just stuck by a doorway going back and forth over and over saying NO_PATH at either side. I hoped it was just due to my paths being covered by new walls and would resolve itself. However after 12 hours its still happening. 

![](https://i.gyazo.com/0d377861601ba99ce197f83a9d584411.png)

![](https://i.gyazo.com/385745a6908d4204067c7d19a4fd93e1.png)

**Comment by Dasku** [comment]
Is it possible to reset all routes and route data?

**Comment by cyberblast** [comment]
Hi Dasku, have you been able to solve the path problem? Can't find your comments anymore here on github!?

If it's still occurring you should try to set ROUTE_PRECALCULATION to false. 
Has been set to true with one of the latest commits. 

The mentioned routeRange Memory only stores room ranges (taking into account available exits and resulting room-routes).

**Comment by Dasku** [comment]
Hey thanks for responding. After I wrote the message I saw there was newer
code so I grabbed that and deleted my message in the hopes it would sort
it.

Just came back and the problem was still happening, just turned
ROUTE_PRECALCULATION to false and it seems to have sorted it!

Thanks a lot!

**Comment by cyberblast** [comment]
Ok, great! :) 
But I wonder why that precalculation is still making such problems :/ 
Will probably require an observer for the "owner" evaluation to work better. 
Going to set to false by default again...
