### ISSUE TITLE
Unable to determine working location for upgrader

### ISSUE THREAD

**Issue by Dasku** [ScreepsGamers/screeps.behaviour-action-pattern#226]
Hey, came home to this error today, no idea why, any suggestions?

![image](https://cloud.githubusercontent.com/assets/22677773/19530008/f32c6938-9629-11e6-8f07-eebb6fd7b092.png)

**Comment by cyberblast** [comment]
**Reason:** 
This is because you have a container near the controller & a link. Thats good so far. 
But the upgrader tries to find a position where it is next to both, which is not possible with this positions. So it doesn't know what to do. 
**Solution:** 
You need to place container and link somewhat closer to each other. so that there is at least one position for the upgrader where it is directly adjacent to oboth and also within range (3) of the controller. 
**Comment:** 
This could be considered a bug. but I'd prefer to see it as 'by design' for the moment. Would take a lot of time and messy code to handle that in a way so that the upgrader moves between them. while not moving elsewhere. I think there are currently more important things on the agenda ;) 
Sorry for the inconvenience...

**Comment by Dasku** [comment]
Ahh ok this makes sense, I'd suggest not changing it as it works perfectly in my other room, this one was just a bit cramped for space, the link is actually connected to another source at the other side of the room. Ill move the centre link away from the controller and container. Thanks a lot!

**Comment by cyberblast** [comment]
Ah ok, you want to make it the link for the storage. 
* Storage needs to be in range of 2 to associated with the link
* Controller needs to be in range of 4 to be associated with the link
* Sources need to be in range of 2 to be associated with the link

No guarantee what happens to mixed associations 😆
