### ISSUE TITLE
Invading

### ISSUE THREAD

**Issue by ValkyrX** [ScreepsGamers/screeps.behaviour-action-pattern#249]
Hi, so i have an issue when invading, if i set a flag red/red to invade a room all my warriors and melee etc goto that room, however if there is a wall they do not attack it, even if i set orange/orange or orange/yellow, this means that although i can send my troops in they dont attack walls or ramparts

**Comment by Dasku** [comment]
You need a privateer (or creep with WORK) to dismantle walls. I use a Orange/Yellow flag on the wall I want to dismantle. Then a Red/Green in the room to trigger a privateer who will dismantle. 

I put my yellow flag near the wall so the fighters can rush through once the wall is open.

**Comment by cyberblast** [comment]
Hi, 
yes Dasku is right. dismantling requires WORK => e.g. privateers. 
but they will not move there unless you place an exploit flag. (max 2 rooms range). 

But orange/orange should work :/ 

maybe delete the red/red and only place the orange/orange. reset the red/red afterwards

**Comment by Dasku** [comment]
I did try that myself yesterday and I couldn't get my ranger to attack the walls. Only dismantle with Orange/Yellow worked for me. This could be a possible bug.

**Comment by cyberblast** [comment]
\*sigh*  
ok I'll create an issue for the orange/orange

**Comment by Dasku** [comment]
Do you want to fix it though? (or is it a bug?) When people attack me they generally come with a tank which has WORK on it which they use to attack my walls/base. I have limited experience with this but could it be that you have to use WORK to destroy a normal wall? Also when you dismantle a wall you get energy back, isn't that preferential/more advantageous to destroying and getting nothing back?

**Comment by cyberblast** [comment]
it depends ^^

You are also able to destroy a wall the "normal" way. 

when in combat/invasion I don't care about the energy that wall would give. I need to get in, no matter how... 

dismantle is more effective. but you need extra creeps or extra parts on the front. that again is expensive. 

so .. there is no simple answer I guess, there are always several options...

**Comment by Dasku** [comment]
Hmm good point. Maybe the Orange/Orange is needed then for the times you want to destroy a wall as quickly as possible.

**Comment by Gestic** [comment]
dunno, this worked for me a few weeks ago as to what op did to walls while attacking without dismantleing. i found that if  you place the red flag the creeps just bump into walls/ramps. i had to place yellow flag in base then orange flags work. this has now changed as i just found out.

**Comment by ValkyrX** [comment]
so what is the procedure for invading then ?  do i place a red/red and a orange/orange on the wall ? im a bit confused with how i get past the walls , also how do you guys get so many attackers as mine only spawns one warrior per yellow/yellow ?

**Comment by cyberblast** [comment]
Set the orange flag first. that should work better. but I will need to run some tests first. 

I believe it's like that: when you have a red in room and set an orange afterwards, creeps (already in that room) got their targets already. so they are not interested in that orange flag until their target is gone. The target is not the flag, but some creep or tower or something. 
It should be sufficient to set an orange alone to have all creeps attack that wall/structure. but you will need to place a red soon enough, otherwise your creeps will go once the wall is broken. 
It should be sufficient if you create the red one loop after the orange. All creeps should then get the orange target first. 

You can get more attackers by placing more yellow flags or manipulating creep.setup.warrior.maxCount (or for melee or ranger or healer).

**Comment by ValkyrX** [comment]
Thanks alot i will see what happens and use orange flag first

**Comment by cyberblast** [comment]
#250 remains open to handle the issue, will close this one
